#!/bin/bash
WLAN=$1     # The name Of the wireless adapter
SSID=$2     # The SSID to extract RSSI from
SAMPLES=$3  # The number of times to sample the RSSI


# USAGE
# getRSSI wlan0 DIRECT-EB-HP 10

COUNTER=0

while [  $COUNTER -lt $SAMPLES ]; do

    cmd="sudo iw $WLAN scan | egrep '$SSID|signal' | egrep -B1 '$SSID' | grep signal"
    RSSI=`eval "$cmd" 2> /dev/null`
    
    if [ $? -eq 0 ]; then
    
        RSSI=($RSSI)
        echo ${RSSI[1]}
        let COUNTER=COUNTER+1 

    fi

done
